# -*- coding: utf-8 -*-
"""PLOTS_HPS_CNN_nested.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Kd8a0TDM3LKDRMVAiIF-qvJSdEyMUuB

#IMPORTS
"""

!pip install scikeras
!pip install tensorflow

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np # Import numpy for potential future use

from matplotlib import pyplot as plt

import h5py
import json
from numpy import argwhere

from sklearn.model_selection import train_test_split
import numpy as np

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np


import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
import threading # Usaremos threading para garantir a segurança da thread
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

import numpy as np
import tensorflow as tf
from tensorflow import keras
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Dropout, Flatten, Dense
from tensorflow.keras.optimizers import Adam, SGD
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Before creating the plot, set the desired font size and name
plt.rcParams['font.size'] = 12  # Change the default font size
plt.rcParams['font.family'] = 'serif'  # Change the default font family (e.g., 'serif', 'sans-serif', 'monospace')

# You can also change these settings for specific text elements if needed.
# For example, to change the title font size:
# plt.title('Plot Title', fontsize=16)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("pinxau1000/radioml2018")

print("Path to dataset files:", path)

h5py_path = path + '/GOLD_XYZ_OSC.0001_1024.hdf5'
modulation_classes_path = path + '/classes-fixed.json'
# Open the dataset
hdf5_file = h5py.File(h5py_path, 'r')
# Load the modulation classes. You can also copy and paste the content of classes-fixed.txt.
modulation_classes = json.load(open(modulation_classes_path, 'r'))

# Read the HDF5 groups
data = hdf5_file['X']
modulation_onehot = hdf5_file['Y']
snr = hdf5_file['Z']

# Load all data from the datasets in the HDF5 file
X = data
Y = modulation_onehot
Z = snr

# Convert one-hot encoded labels to numerical labels
y = np.argmax(Y, axis=1)

# ══════════════════════════════════════════════════════════════════════════════
# SEED GLOBAL — garante reprodutibilidade total entre execuções
# Cole esta célula como a PRIMEIRA célula de código do notebook
# ══════════════════════════════════════════════════════════════════════════════

import random
import numpy as np
import torch

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

# Garante operações determinísticas na GPU (pequeno custo de performance)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark     = False

print(f"✅ Seeds fixadas: SEED={SEED}")
print(f"   random     : OK")
print(f"   numpy      : OK")
print(f"   torch CPU  : OK")
print(f"   torch CUDA : OK")
print(f"   cudnn det. : OK")

import torch
import os
from tqdm import tqdm

def train_and_validate(model, train_loader, val_loader, criterion, optimizer,
                       scheduler=None, epochs=10, save_name="best_model"):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    # 📁 Diretório padrão do Colab
    SAVE_DIR = "/content"
    os.makedirs(SAVE_DIR, exist_ok=True)

    best_val_acc = 0.0
    best_model_path = None
    epochs_no_improve = 0

    # 🔥 Early stopping baseado no scheduler
    if scheduler is not None and isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
        early_stop_patience = scheduler.patience * 2
    else:
        early_stop_patience = 10

    print(f"🛑 Early Stopping patience: {early_stop_patience}")

    for epoch in range(epochs):

        # ── TREINO ──
        model.train()
        train_loss, train_correct, train_total = 0, 0, 0

        pbar_train = tqdm(train_loader, desc=f"Época {epoch+1}/{epochs} [Treino]")

        for inputs, labels in pbar_train:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            _, predicted = outputs.max(1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()

        # ── VALIDAÇÃO ──
        model.eval()
        val_loss, val_correct, val_total = 0, 0, 0

        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)

                outputs = model(inputs)
                loss = criterion(outputs, labels)

                val_loss += loss.item()
                _, predicted = outputs.max(1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

        # ── MÉTRICAS ──
        final_train_loss = train_loss / len(train_loader)
        final_train_acc  = 100. * train_correct / train_total
        final_val_loss   = val_loss / len(val_loader)
        final_val_acc    = 100. * val_correct / val_total

        current_lr = optimizer.param_groups[0]['lr']

        # ── CHECKPOINT MELHOR ──
        if final_val_acc > best_val_acc:
            best_val_acc = final_val_acc
            epochs_no_improve = 0

            # 🧹 remove modelo anterior
            if best_model_path and os.path.exists(best_model_path):
                os.remove(best_model_path)

            # 🏷 nome com métricas
            filename = (
                f"{save_name}_ep{epoch+1:03d}"
                f"_acc{final_val_acc:.2f}"
                f"_lr{current_lr:.2e}.pth"
            )

            best_model_path = os.path.join(SAVE_DIR, filename)

            torch.save({
                'epoch': epoch + 1,
                'val_acc': final_val_acc,
                'val_loss': final_val_loss,
                'lr': current_lr,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
            }, best_model_path)

            print(f"💾 Novo melhor modelo salvo:")
            print(f"   📁 {best_model_path}")

        else:
            epochs_no_improve += 1

        # ── SCHEDULER ──
        if scheduler is not None:
            if isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
                scheduler.step(final_val_acc)  # 🔥 melhor usar ACC
            else:
                scheduler.step()

        # ── LOG ──
        print(f"\nÉpoca {epoch+1}: "
              f"Train Loss: {final_train_loss:.4f} | Train Acc: {final_train_acc:.2f}% | "
              f"Val Loss: {final_val_loss:.4f} | Val Acc: {final_val_acc:.2f}% | "
              f"LR: {current_lr:.2e}")

        # ── EARLY STOP ──
        if epochs_no_improve >= early_stop_patience:
            print(f"\n🛑 Early stopping ativado na época {epoch+1}")
            break

    print(f"\n✅ Melhor Val Acc: {best_val_acc:.2f}%")
    print(f"📁 Modelo salvo em: {best_model_path}")

    return best_model_path

def get_indices_by_snr(target_snrs):
    """
    Separates and returns indices corresponding to specified SNR values.

    Args:
        target_snrs (list or np.ndarray): A list or array of SNR values
                                          (e.g., [-20, -10, 0, 10]) to filter by.

    Returns:
        np.ndarray: A sorted numpy array of indices from the original dataset (X, Y, Z, y)
                    where the SNR matches one of the target_snrs.
    """
    # Convert target_snrs to a set for efficient lookup
    target_snrs_set = set(target_snrs)

    # Get the SNR values from the Z array (assuming Z is globally available)
    # Z[:, 0] extracts the SNR column
    all_snr_values = Z[:, 0]

    # Find indices where the SNR value is in the target_snrs_set
    matching_indices = np.where(np.isin(all_snr_values, list(target_snrs_set)))[0]

    return np.sort(matching_indices)

# Example Usage:
# Let's say you want indices for SNR values of -20dB, 0dB, and 10dB
# desired_snrs = [-20, 0, 10]
# selected_snr_indices = get_indices_by_snr(desired_snrs)
#
# print(f"Found {len(selected_snr_indices)} samples with SNR in {desired_snrs}")
#
# # You can then use these indices to access the corresponding data
# # X_filtered_by_snr = X[selected_snr_indices]
# # y_filtered_by_snr = y[selected_snr_indices]
# # Z_filtered_by_snr = Z[selected_snr_indices]

# The previous content of this cell was likely a print statement.
# I'll add a simple print to confirm the function is defined.

def get_samples_by_snr(target_snrs):
    """
    Returns data samples (X, Y, Z, y) corresponding to specified SNR values.

    Args:
        target_snrs (list or np.ndarray): A list or array of SNR values
                                          (e.g., [-20, -10, 0, 10]) to filter by.

    Returns:
        tuple: A tuple containing X_filtered, Y_filtered, Z_filtered, y_filtered
               for the selected SNR values.
    """
    # Use the existing function to get indices for the target SNRs
    selected_indices = get_indices_by_snr(target_snrs)

    # Use these indices to subset the global data arrays
    X_filtered = X[selected_indices]
    Y_filtered = Y[selected_indices]
    Z_filtered = Z[selected_indices]
    y_filtered = y[selected_indices]

    print(f"\nSubset created with {len(selected_indices)} samples for SNR values: {target_snrs}.")
    print(f"Shape of X_filtered: {X_filtered.shape}")
    print(f"Shape of Y_filtered: {Y_filtered.shape}")
    print(f"Shape of Z_filtered: {Z_filtered.shape}")
    print(f"Shape of y_filtered: {y_filtered.shape}")

    return X_filtered, Y_filtered, Z_filtered, y_filtered, selected_indices

print("Function 'get_samples_by_snr' defined.")

def subset_snr (target_snrs, frac):
    X_snr, Y_snr, Z_snr, y_snn, selected_indices = get_samples_by_snr(target_snrs)

    ind_snr_frac, ind_lixo, Y_snr_frac, Ysnr_lixo = train_test_split(
        selected_indices,
        Y_snr,
        test_size=1-frac,
        random_state=42,
        stratify=Y_snr
    )

    ind_snr_frac = np.sort(ind_snr_frac)
    X_filtered = X[ind_snr_frac]
    Y_filtered = Y[ind_snr_frac]
    Z_filtered = Z[ind_snr_frac]
    y_filtered = y[ind_snr_frac]

    print(f"\nSubset created with {len(selected_indices)} samples for SNR values: {target_snrs}.")
    print(f"Shape of X_filtered: {X_filtered.shape}")
    print(f"Shape of Y_filtered: {Y_filtered.shape}")
    print(f"Shape of Z_filtered: {Z_filtered.shape}")
    print(f"Shape of y_filtered: {y_filtered.shape}")

    return X_filtered, Y_filtered, Z_filtered, y_filtered, ind_snr_frac

def split (indices, lables):
  train_val_indices, test_indices, train_val_lables, test_lables = train_test_split(
        indices,
        lables,
        test_size=0.2,
        random_state=42,
        stratify=lables
    )

  train_indices, val_indices, train_lables, val_lables = train_test_split(
        train_val_indices,
        train_val_lables,
        test_size=0.25,
        random_state=42,
        stratify=train_val_lables
    )

  train_indices_sorted = np.sort(train_indices)
  val_indices_sorted = np.sort(val_indices)
  test_indices_sorted = np.sort(test_indices)

  return train_indices_sorted, val_indices_sorted, test_indices_sorted

# ══════════════════════════════════════════════════════════════════════════════
# ACESSO UNIVERSAL AO GOOGLE DRIVE — via OAuth (conta pessoal)
#
# Service Accounts NÃO funcionam com contas Gmail pessoais para gravar
# arquivos (elas não têm cota de armazenamento própria e só escrevem em
# Shared Drives, que exigem Google Workspace pago). Por isso usamos OAuth
# com um token da própria conta jmarcopereira29@gmail.com: uma vez gerado,
# esse token funciona em QUALQUER ambiente (Colab, servidor, Jupyter local),
# sem precisar logar de novo, e sempre acessa o Drive dessa mesma conta.
#
# ── COMO CONFIGURAR (faça isso uma única vez) ──────────────────────────────
# 1. Acesse https://console.cloud.google.com/apis/credentials
#    (crie um projeto, se ainda não tiver um)
# 2. Clique em "+ CRIAR CREDENCIAIS" → "ID do cliente OAuth"
#    - Se pedir para configurar a "Tela de consentimento OAuth" antes, escolha
#      tipo "Externo", preencha nome/e-mail, e em "Test users" adicione
#      jmarcopereira29@gmail.com
#    - Tipo de aplicativo: "App para computador" (Desktop app)
#    - Dê um nome e clique em Criar
# 3. Baixe o JSON gerado e salve como 'client_secret.json'
# 4. No SEU COMPUTADOR (onde tem navegador), rode o script auxiliar
#    'gerar_token_drive.py' (fornecido separadamente). Ele abre o navegador,
#    você loga como jmarcopereira29@gmail.com e autoriza o acesso.
#    Isso gera o arquivo 'token.json'.
# 5. Suba 'token.json' (e 'client_secret.json') para qualquer ambiente onde
#    este notebook for rodar — não precisa repetir o login.
# ══════════════════════════════════════════════════════════════════════════════

!pip install -q google-api-python-client google-auth google-auth-oauthlib

import os
import io
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload, MediaIoBaseDownload
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request

# ▶▶ AJUSTE APENAS ESTA LINHA ◀◀
DRIVE_FOLDER_ID = "1E2bJyP18S4xq4OhBbvgryJ0Oc5Hm_tv2"

SCOPES              = ["https://www.googleapis.com/auth/drive"]
CLIENT_SECRET_FILE  = "client_secret.json"
TOKEN_FILE          = "token.json"

if not os.path.exists(TOKEN_FILE):
    raise FileNotFoundError(
        f"Não encontrei '{TOKEN_FILE}'.\n"
        f"Rode o script 'gerar_token_drive.py' no seu computador (com "
        f"navegador) logado como jmarcopereira29@gmail.com para gerar esse "
        f"arquivo, depois faça upload dele (e do 'client_secret.json') "
        f"aqui neste ambiente."
    )

_drive_creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

# Renova o token automaticamente se estiver expirado
if _drive_creds.expired and _drive_creds.refresh_token:
    _drive_creds.refresh(Request())
    with open(TOKEN_FILE, "w") as f:
        f.write(_drive_creds.to_json())

_drive_service = build("drive", "v3", credentials=_drive_creds)

# Confirma qual conta está autenticada
_about = _drive_service.about().get(fields="user").execute()
print(f"✅ Conectado ao Google Drive como: {_about['user']['emailAddress']}")
print(f"   Pasta raiz (Drive Folder ID): {DRIVE_FOLDER_ID}")


# ══════════════════════════════════════════════════════════════════════════════
# FUNÇÕES DE SINCRONIZAÇÃO — usadas em vez de leitura/escrita direta no Drive
# ══════════════════════════════════════════════════════════════════════════════

_drive_folder_cache = {}  # relpath da pasta -> folder_id (evita buscas repetidas)


def _drive_get_or_create_folder(rel_dir):
    """Garante que a árvore de pastas 'rel_dir' existe no Drive e retorna o ID da pasta final."""
    if rel_dir in ("", "."):
        return DRIVE_FOLDER_ID
    if rel_dir in _drive_folder_cache:
        return _drive_folder_cache[rel_dir]

    parent_id = DRIVE_FOLDER_ID
    partial = ""
    for part in rel_dir.replace("\\", "/").split("/"):
        if not part:
            continue
        partial = f"{partial}/{part}" if partial else part
        if partial in _drive_folder_cache:
            parent_id = _drive_folder_cache[partial]
            continue

        query = (
            f"'{parent_id}' in parents and name = '{part}' "
            f"and mimeType = 'application/vnd.google-apps.folder' and trashed = false"
        )
        resp = _drive_service.files().list(q=query, fields="files(id, name)").execute()
        files = resp.get("files", [])

        if files:
            folder_id = files[0]["id"]
        else:
            metadata = {
                "name": part,
                "mimeType": "application/vnd.google-apps.folder",
                "parents": [parent_id],
            }
            folder = _drive_service.files().create(body=metadata, fields="id").execute()
            folder_id = folder["id"]

        _drive_folder_cache[partial] = folder_id
        parent_id = folder_id

    return parent_id


def _drive_find_file(rel_dir, filename):
    """Retorna o file_id de 'filename' dentro de 'rel_dir' no Drive, ou None se não existir."""
    parent_id = _drive_get_or_create_folder(rel_dir)
    query = f"'{parent_id}' in parents and name = '{filename}' and trashed = false"
    resp = _drive_service.files().list(q=query, fields="files(id, name)").execute()
    files = resp.get("files", [])
    return files[0]["id"] if files else None


def drive_push(local_path):
    """
    Envia (cria ou atualiza) um arquivo local para o Drive, espelhando o
    caminho relativo a DRIVE_BASE. Ex.: DRIVE_BASE/PSK/kfold_summary.json
    """
    rel_path = os.path.relpath(local_path, DRIVE_BASE)
    rel_dir  = os.path.dirname(rel_path)
    filename = os.path.basename(rel_path)

    parent_id   = _drive_get_or_create_folder(rel_dir)
    existing_id = _drive_find_file(rel_dir, filename)
    media       = MediaFileUpload(local_path, resumable=True)

    if existing_id:
        _drive_service.files().update(fileId=existing_id, media_body=media).execute()
    else:
        metadata = {"name": filename, "parents": [parent_id]}
        _drive_service.files().create(body=metadata, media_body=media, fields="id").execute()


def drive_pull(local_path):
    """
    Baixa do Drive para 'local_path' (espelhando o caminho relativo a
    DRIVE_BASE), se o arquivo existir remotamente. Retorna True se baixou,
    False se não havia nada no Drive ainda.
    """
    rel_path = os.path.relpath(local_path, DRIVE_BASE)
    rel_dir  = os.path.dirname(rel_path)
    filename = os.path.basename(rel_path)

    file_id = _drive_find_file(rel_dir, filename)
    if file_id is None:
        return False

    os.makedirs(os.path.dirname(local_path), exist_ok=True)
    request = _drive_service.files().get_media(fileId=file_id)
    with io.FileIO(local_path, "wb") as fh:
        downloader = MediaIoBaseDownload(fh, request)
        done = False
        while not done:
            _, done = downloader.next_chunk()
    return True

from torch.utils.data import Dataset
class H5PyDataset(Dataset):
    def __init__(self, h5_filepath, data_X_name, data_Y_name, data_Z_name, indices, formats):
        self.h5_filepath = h5_filepath
        self.data_X_name = data_X_name
        self.data_Y_name = data_Y_name
        self.indices = np.array(indices)
        self.formats = formats
        self.file = None

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        # Abre o arquivo apenas uma vez por worker
        if self.file is None:
            self.file = h5py.File(self.h5_filepath, 'r')
            self.X_data = self.file[self.data_X_name]
            self.Y_data = self.file[self.data_Y_name]

        # Pega o índice real baseado na sua lista de sorteados
        real_idx = self.indices[idx]

        # Busca UMA amostra (1024, 2)
        x = self.X_data[real_idx, :]
        y = self.Y_data[real_idx]

        # Normalização Individual
        # mean = x.mean()
        # std = x.std()
        # x = (x - mean) / (std + 1e-8)

        # Trata o Label
        if self.formats == 0:
            # Se y for um vetor (One-Hot), pega o índice da classe
            if hasattr(y, "__len__"):
                y = np.argmax(y)

        # Conversão para Tensor
        x_tensor = torch.from_numpy(x).float() # [1024, 2]
        x_tensor = x_tensor.permute(1, 0)      # [2, 1024] (Canais primeiro)
        y_tensor = torch.tensor(y).long()      # Valor escalar

        return x_tensor, y_tensor

num_samples = X.shape[0]
indices = np.arange(num_samples) #selected_indices_sorted
lables = np.column_stack((y, Z))

train_indices_sorted, val_indices_sorted, test_indices_sorted = split(indices, lables)

from torch.utils.data import DataLoader, BatchSampler, RandomSampler, SequentialSampler, random_split

# 1. Dataset (Certifique-se que o __getitem__ aceita a lista de índices como discutimos)
# Dataset de Treino
train_dataset = H5PyDataset(
    h5_filepath=h5py_path,
    data_X_name='X',
    data_Y_name='Y',
    data_Z_name='Z',
    indices=train_indices_sorted,  # Seus índices de treino
    formats=0
)

# Dataset de Validação
val_dataset = H5PyDataset(
    h5_filepath=h5py_path,
    data_X_name='X',
    data_Y_name='Y',
    data_Z_name='Z',
    indices=val_indices_sorted,    # Seus índices de validação
    formats=0
)

test_dataset = H5PyDataset(
    h5_filepath=h5py_path,
    data_X_name='X',
    data_Y_name='Y',
    data_Z_name='Z',
    indices=test_indices_sorted,    # Seus índices de validação
    formats=0
)

batch_size = 64

# Remova o BatchSampler e o collate_fn.
# Use shuffle=True para o treino e shuffle=False para validação.
train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,          # Isso substitui o RandomSampler
    drop_last=False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False,         # Isso substitui o SequentialSampler
    drop_last=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,         # Isso substitui o SequentialSampler
    drop_last=False
)

# ══════════════════════════════════════════════════════════════════════════════
# DATALOADERS COM SEED CONTROLADA
# ══════════════════════════════════════════════════════════════════════════════

import torch
from torch.utils.data import DataLoader

SEED       = 42
batch_size = 64

# Gerador dedicado para o DataLoader — controla o shuffle entre épocas
g = torch.Generator()
g.manual_seed(SEED)

def seed_worker(worker_id):
    """Garante seeds determinísticas nos workers do DataLoader."""
    worker_seed = torch.initial_seed() % (2**32)
    np.random.seed(worker_seed)
    random.seed(worker_seed)

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    drop_last=False,
    num_workers=0,
    persistent_workers=False,
    generator=g,               # controla a ordem do shuffle
    worker_init_fn=seed_worker # controla seeds dos workers (se num_workers>0)
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False,
    drop_last=False,
    num_workers=0,
    persistent_workers=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,
    drop_last=False,
    num_workers=0,
    persistent_workers=False
)

import torch.nn as nn
class CNN(nn.Module):
    def __init__(self, num_classes):
        super(CNN, self).__init__()

        self.features = nn.Sequential(
            nn.Conv1d(2, 64, kernel_size=11, padding=3),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.MaxPool1d(2),

            nn.Conv1d(64, 128, kernel_size=7, padding=2),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.MaxPool1d(2),

            nn.Conv1d(128, 256, kernel_size=5, padding=1),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.MaxPool1d(2),

            nn.Conv1d(256, 512, kernel_size=3, padding=1),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.MaxPool1d(2),

            nn.Conv1d(512, 1024, kernel_size=3, padding=1),
            nn.BatchNorm1d(1024),
            nn.ReLU(),
            nn.MaxPool1d(2)


        )

        # Técnica para detectar o tamanho do flatten automaticamente:
        self.flatten = nn.Flatten()
        with torch.no_grad():
            # Passamos um dado "dummy" de teste para ver o que sai das convs
            dummy_input = torch.zeros(1, 2, 1024)
            dummy_output = self.features(dummy_input)
            self.n_flatten = dummy_output.view(1, -1).size(1)

        print(f"Tamanho detectado para o Flatten: {self.n_flatten}")

        self.classifier = nn.Sequential(
            nn.Linear(self.n_flatten, 512),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.flatten(x)
        x = self.classifier(x)
        return x

# ══════════════════════════════════════════════════════════════════════════════
# ANÁLISE DE PROGRESSO — substitui a célula de TREINO
# SOMENTE LEITURA: baixa (drive_pull) os resultados já salvos no Drive e plota.
# Esta célula NUNCA grava/edita os arquivos originais de progresso, e NUNCA
# chama drive_push (redefinida abaixo para travar caso algo tente chamá-la).
#
# Pré-requisito: rode antes a célula de acesso ao Drive (a que define
# _drive_service, drive_pull, drive_push, DRIVE_FOLDER_ID).
# ══════════════════════════════════════════════════════════════════════════════

import os, json
from collections import Counter, defaultdict
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ▶▶ Precisa ser IGUAL ao DRIVE_BASE usado durante o treino/busca ◀◀
DRIVE_BASE  = "/content/drive_cache/radioml_sessions"
GRUPOS_ALVO = ["ASK", "PSK", "APSK", "QAM", "AM", "FM"]

# Pasta de saída dos gráficos/tabela — PROPOSITALMENTE fora de DRIVE_BASE,
# para não ter nenhuma chance de colidir/sobrescrever os arquivos originais.
OUT_DIR = "/content/kfold_analysis"
os.makedirs(OUT_DIR, exist_ok=True)

# ── TRAVA DE SEGURANÇA ────────────────────────────────────────────────────────
def drive_push(*args, **kwargs):
    raise RuntimeError(
        "🚫 Esta célula é somente leitura — drive_push está desabilitada aqui "
        "de propósito para garantir que nada seja escrito no Drive."
    )


def _read_only_json(local_path):
    """Lê um JSON em modo estritamente leitura ('r').
    Nunca abre em 'w'/'a'. Se não existir localmente, tenta baixar (só
    download, nunca upload) via drive_pull."""
    if not os.path.exists(local_path):
        drive_pull(local_path)  # apenas download; nunca upload
    if not os.path.exists(local_path):
        return None
    with open(local_path, "r", encoding="utf-8") as f:  # 'r' = somente leitura
        return json.load(f)


def carregar_resultados(modelo):
    local_path = os.path.join(DRIVE_BASE, modelo, "kfold_fold_results.json")
    data = _read_only_json(local_path)
    return data or []


def agrupar_por_label(results):
    by_label = defaultdict(list)
    for r in results:
        by_label[r["label"]].append(r)
    return by_label


def moda_int(values):
    """Moda desconsiderando as casas decimais (trunca para inteiro)."""
    if not values:
        return np.nan
    ints = [int(v) for v in values]
    counts = Counter(ints)
    maxc = max(counts.values())
    return sorted(v for v, c in counts.items() if c == maxc)[0]


def plot_curvas_epocas(by_label, modelo):
    """Uma curva por arquitetura tentada: gráfico do melhor fold e do pior fold."""
    if not by_label:
        return
    for kind, titulo in (("best", "melhor fold"), ("worst", "pior fold")):
        fig, ax = plt.subplots(figsize=(11, 6.5))
        plotou = False
        for label, folds in sorted(by_label.items()):
            com_hist = [r for r in folds if r.get("history")]
            if not com_hist:
                continue
            ordenado = sorted(com_hist, key=lambda r: r["best_val_acc"])
            escolhido = ordenado[-1] if kind == "best" else ordenado[0]
            ep  = [h["epoch"] for h in escolhido["history"]]
            acc = [h["val_acc"] for h in escolhido["history"]]
            ax.plot(ep, acc, label=f"{label} (fold {escolhido['fold']+1}, "
                                    f"{escolhido['best_val_acc']:.2f}%)")
            plotou = True
        if not plotou:
            plt.close(fig)
            continue
        ax.set_xlabel("Época")
        ax.set_ylabel("Acurácia de validação (%)")
        ax.set_title(f"{modelo} — acurácia por época ({titulo} de cada arquitetura)")
        ax.legend(fontsize=7.5, loc="lower right")
        ax.grid(alpha=0.3)
        fig.tight_layout()
        fname = os.path.join(OUT_DIR, f"{modelo}_epochs_{kind}_fold.png")
        fig.savefig(fname, dpi=150)  # só grava o PNG de saída, fora do DRIVE_BASE
        plt.show()
        plt.close(fig)
        print(f"  📈 {fname}")


def plot_params_vs_acc(by_label, modelo):
    labels, nparams, medias = [], [], []
    for label, folds in by_label.items():
        accs = [r["best_val_acc"] for r in folds]
        if not accs:
            continue
        labels.append(label)
        nparams.append(folds[0]["n_params"])
        medias.append(float(np.mean(accs)))
    if not labels:
        return
    fig, ax = plt.subplots(figsize=(9, 6.5))
    ax.scatter(nparams, medias, s=70)
    for x, y, lab in zip(nparams, medias, labels):
        ax.annotate(lab, (x, y), fontsize=7, xytext=(4, 4), textcoords="offset points")
    ax.set_xscale("log")
    ax.set_xlabel("Número de parâmetros (escala log)")
    ax.set_ylabel("Acurácia média de validação (%)")
    ax.set_title(f"{modelo} — parâmetros x acurácia média")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fname = os.path.join(OUT_DIR, f"{modelo}_params_vs_acc.png")
    fig.savefig(fname, dpi=150)
    plt.show()
    plt.close(fig)
    print(f"  📈 {fname}")


def montar_tabela(by_label, modelo):
    linhas = []
    for label, folds in by_label.items():
        accs = [r["best_val_acc"] for r in folds]
        if not accs:
            continue
        linhas.append({
            "modelo"          : modelo,
            "arquitetura"     : label,
            "n_params"        : folds[0]["n_params"],
            "folds_concluidos": len(accs),
            "media_acc"       : round(float(np.mean(accs)), 2),
            "max_acc"         : round(float(np.max(accs)), 2),
            "min_acc"         : round(float(np.min(accs)), 2),
            "moda_acc_int"    : moda_int(accs),
            "std_acc"         : round(float(np.std(accs)), 2),
        })
    return linhas


# ══════════════════════════════════════════════════════════════════════════════
# EXECUÇÃO — apenas leitura + geração dos gráficos/tabela
# ══════════════════════════════════════════════════════════════════════════════
tabela_geral = []
for modelo in GRUPOS_ALVO:
    print(f"\n=== {modelo} ===")
    resultados = carregar_resultados(modelo)
    if not resultados:
        print(f"  ⚠ nenhum resultado encontrado para '{modelo}', pulando")
        continue
    by_label = agrupar_por_label(resultados)
    plot_curvas_epocas(by_label, modelo)
    plot_params_vs_acc(by_label, modelo)
    tabela_geral.extend(montar_tabela(by_label, modelo))

if tabela_geral:
    df = pd.DataFrame(tabela_geral).sort_values(["modelo", "media_acc"],
                                                 ascending=[True, False])
    csv_path = os.path.join(OUT_DIR, "tabela_resultados.csv")
    df.to_csv(csv_path, index=False)  # só grava o CSV de saída, fora do DRIVE_BASE
    print(f"\n📋 Tabela salva em: {csv_path}\n")
    try:
        display(df)   # no Colab/Jupyter mostra como tabela formatada
    except NameError:
        print(df.to_string(index=False))
else:
    print("\nNenhum dado encontrado em nenhum grupo.")